services:
    _defaults:
        public: true

    # If you need to access services in a ajax, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with ajax. For example:
    #
    # ajax.App\Service\MyService: '@App\Service\MyService'
